version: '3.8'

services:
  bot:
    build: .
    container_name: discord-bot
    restart: unless-stopped
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - SPOTIPY_CLIENT_ID=${SPOTIFY_CLIENT_ID}
      - SPOTIPY_CLIENT_SECRET=${SPOTIFY_CLIENT_SECRET}
      - SPOTIFY_PLAYLIST_ID=${SPOTIFY_PLAYLIST_ID}
